services:
  rod:
    image: ${IMAGE:-loglug/rod:nvidia-latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      ROD_GPU_DEVICE: 0