# compose.yaml
services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: rodadmin
      DOCKER_INFLUXDB_INIT_PASSWORD: rodpassword
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: D0NTSH@R3M3!!!
      DOCKER_INFLUXDB_INIT_ORG: rod
      DOCKER_INFLUXDB_INIT_BUCKET: rod_data
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
volumes:
  influxdb2-data:
  influxdb2-config:

  rod:
    image: loglug/rod:amd-latest
    ports:
      - 5000:5000
    environment:
      ROD_HOSTNAME: localhost
      ROD_PORT: 5000
      ROD_DATA_PATH: /uploads
      INFLUXDB_TOKEN: D0NTSH@R3M3!!!
      # INFLUXDB_TOKEN_SECRET: /run/secrets/influxdb-token # This will take precedence over INFLUXDB_TOKEN
      INFLUXDB_ORG: rod
      INFLUXDB_URL: influxdb2
      INFLUXDB_BUCKET: rod_data
    # secrets:
    #   influxdb-token:
    #     file:
    #       ./.env.influxdb-token
    volumes:
      rod-data:
        target: /uploads