FROM pytorch/pytorch:2.9.0-cuda12.8-cudnn9-runtime
WORKDIR /app
COPY nvidia_requirements.txt .
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r nvidia_requirements.txt
COPY . .
CMD ["python", "-u", "app.py"]
#TODO: write custom startup script