FROM python:3.13.9-slim
WORKDIR /app
COPY amd_requirements.txt .
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r amd_requirements.txt
COPY . .
CMD ["python", "app.py"]
#TODO: write custom startup script