name: trains
channels:
  - defaults
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - click=8.1.7
  - expat=2.6.4
  - flask=3.1.0
  - itsdangerous=2.2.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=3.0.2
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.9
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - bidict==0.23.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - dnspython==2.7.0
      - eventlet==0.39.1
      - filelock==3.17.0
      - flask-socketio==5.5.1
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - greenlet==3.1.1
      - h11==0.14.0
      - idna==3.10
      - jinja2==3.1.5
      - kiwisolver==1.4.8
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.1.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-engineio==4.11.2
      - python-socketio==5.12.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - scipy==1.15.1
      - seaborn==0.13.2
      - simple-websocket==1.1.0
      - six==1.17.0
      - sympy==1.13.1
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - ultralytics==8.3.75
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
      - wsproto==1.2.0
